### PR TITLE
Add xml tools

### PR DESCRIPTION
**Pull request by philboeselager**
Add pipe XmlElementSplitter to split one big xml file.
Add sink XmlFilenameWriter to extract filename and store xml into filesystem.

See lobid/lodmill#98.

### CODE REVIEW

**Comment by dr0i** [comment]
In fact, the name "XmlEntitySplitter" is misleading, see e.g. here http://www.ibm.com/developerworks/library/x-entities/ . In know I gave the name, but I error (sometimes). 
This would be the proper moment for renaming.
Do you know a better name? 
The name should hint what it does: "Splits all entities (aka records) residing in one XML document into multiple single XML documents."
Would "XmlRecordSplitter" or "XmlSplitter" be better? "Splitter" maybe is also no good word.
I ask also @jschnasse and @fsteeg , the former of I know knows xml way better than me.

**Comment by fsteeg** [comment]
I like "XmlRecordSplitter".

**Comment by philboeselager** [comment]
Does the XML to be split necessarily consist of records? If so, XmlRecordSplitter is a good, depicting term. Otherwise, I would go for s.th. like XmlSubDivider.

**Comment by dr0i** [comment]
@philboeselager you are right, it's not necessarily a record that's extracted. We use it solely as that, though. Have a look at the junit test at the end of the commit to understand (and correct me if I am wrong).
I looked around and technically what's really "splitted" seems to be called an `XML element` (http://www.w3schools.com/xmL/xml_elements.asp).  
Also, thinking about it, maybe `extractor` is more speaking? Thus the name would be `XmlElementExtractor". 
What do you think?

**Comment by philboeselager** [comment]
Good Point.
"Extractor" vs. "Divider" or "Splitter": It depends on what we assume the input XML is going to be like: if there could be information (i.e . tags) that are completely left unprocessed and is out of interest, "Extractor" is a good term.
If we assume that the input (nearly) completely consists of information to be processed, "Divider" or "Splitter" is more depicting.
Since we don't know, what kind of input XML other users of the framework are going process, "Extractor" is my favourite.
So: +1 for XmlElementExtractor.
Anyway, it looks like a mighty tool if it can have so many different names... :)

**Comment by jschnasse** [comment]
I would simply call it XmlPipe but this already exists. Maybe XmlElementsPipe

**Comment by dr0i** [comment]
So, `Element` is fine.
I decided to name it `XmlElementSplitter` because it also exist a `LineSplitter`. And I decided to move the class into the `pipe` package, because it's really a pipe (as @jschnasse pointed out).
Also I updated the flux-command.properties which is wanted by customers, see e.g. culturegraph/metafacture-core#235.
I made a separate branch https://github.com/hbz/metafacture-core/tree/addXmlTools1 and if that is revised by @philboeselager as ok I would force push it to this branch.

**Comment by fsteeg** [comment]
@dr0i All that code was written by you, right? I'd therefore suggest you amend the author to yourself before pushing to this branch.

**Comment by dr0i** [comment]
Amended. Now ready to be merged.

**Comment by philboeselager** [comment]
Review: +1

**Comment by fsteeg** [comment]
Merged, leaving branch for the pull request against culturegaph.

**Pull request merged**
